package com.sourabh.product_service.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a hierarchical product category.
 * <p>
 * Categories support a tree structure via a self-referencing parent–child
 * relationship. Root categories have a {@code null} parent. Each category
 * name must be unique within its parent scope, enforced by a composite
 * unique constraint on {@code (name, parent_id)}.
 * </p>
 * <p>
 * The entity manages its own UUID generation and audit timestamps through
 * JPA lifecycle callbacks ({@link PrePersist}, {@link PreUpdate}).
 * </p>
 */
@Entity
@Table(name = "category", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"uuid"}),
        @UniqueConstraint(columnNames = {"name", "parent_id"})
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Universally unique identifier exposed to external clients instead of the internal ID. */
    @Column(nullable = false, unique = true, updatable = false)
    private String uuid;

    /** Human-readable category name; must be unique among siblings sharing the same parent. */
    @Column(nullable = false)
    private String name;

    /** Optional long-form description of the category (max 500 characters). */
    @Column(length = 500)
    private String description;

    /** Optional URL pointing to a representative image for this category. */
    @Column(length = 500)
    private String imageUrl;

    /**
     * Parent category in the hierarchy.
     * A {@code null} value indicates that this is a root-level category.
     * Loaded lazily to avoid unnecessary joins when only the current category is needed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    private Category parent;

    /**
     * Child categories belonging to this category.
     * Cascade removal ensures that deleting a parent also removes all descendants.
     */
    @OneToMany(mappedBy = "parent", cascade = CascadeType.REMOVE, orphanRemoval = true)
    @Builder.Default
    private List<Category> children = new ArrayList<>();

    /** Zero-based display order used for sorting categories in the UI. */
    @Column(nullable = false)
    @Builder.Default
    private Integer displayOrder = 0;

    /** Soft-active flag; inactive categories are hidden from public listings. */
    @Column(nullable = false)
    @Builder.Default
    private boolean isActive = true;

    /** Timestamp recording when this category was first persisted. */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /** Timestamp recording the most recent update; {@code null} if never updated. */
    private LocalDateTime updatedAt;

    /**
     * JPA lifecycle callback executed before initial persist.
     * Generates a random UUID if not already set and records the creation timestamp.
     */
    @PrePersist
    protected void onCreate() {
        if (this.uuid == null) this.uuid = UUID.randomUUID().toString();
        if (this.createdAt == null) this.createdAt = LocalDateTime.now();
    }

    /**
     * JPA lifecycle callback executed before every update.
     * Refreshes the {@code updatedAt} timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
