package com.sourabh.product_service.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * JPA entity representing a time-limited flash deal (sale) applied to a product.
 * <p>
 * A flash deal gives a percentage discount on a product for a defined time window
 * ({@code startTime} to {@code endTime}). Deals are created by sellers and
 * automatically deactivated by {@code ExpireFlashDealsScheduler} once they expire.
 * </p>
 * <p>
 * Inherits audit timestamps ({@code createdAt}, {@code updatedAt}) from
 * {@link BaseAuditEntity}.
 * </p>
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "flash_deal")
public class FlashDeal extends BaseAuditEntity {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Universally unique identifier exposed to API consumers. */
    @Column(unique = true, nullable = false)
    private String uuid;

    /**
     * The product to which this flash deal applies.
     * Fetched lazily to avoid unnecessary joins when only deal metadata is needed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Discount percentage applied during the deal (e.g., 15.0 means 15% off). */
    @Column(nullable = false)
    private Double discountPercent;

    /** Inclusive start time of the flash deal window. */
    @Column(nullable = false)
    private LocalDateTime startTime;

    /** Inclusive end time of the flash deal window. */
    @Column(nullable = false)
    private LocalDateTime endTime;

    /** Whether the deal is currently active; set to {@code false} when cancelled or expired. */
    @Column(nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    /** UUID of the seller who created this deal. */
    @Column(nullable = false)
    private String sellerUuid;

    /**
     * JPA lifecycle callback that generates a random UUID before the entity is
     * first persisted, if one has not already been assigned.
     */
    @PrePersist
    private void generateUuid() {
        if (uuid == null) uuid = java.util.UUID.randomUUID().toString();
    }
}
