package com.sourabh.product_service.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * JPA entity representing an image associated with a {@link Product}.
 * <p>
 * A product can have multiple images. The {@code displayOrder} field
 * determines the presentation sequence; an order of {@code 0} conventionally
 * designates the primary/hero image shown in product listings.
 * </p>
 * <p>
 * Inherits audit timestamps ({@code createdAt}, {@code updatedAt}) from
 * {@link BaseAuditEntity}.
 * </p>
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "product_image")
public class ProductImage extends BaseAuditEntity {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The product this image belongs to.
     * Fetched lazily to avoid unnecessary joins when only image metadata is needed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Full URL of the image resource, stored as unlimited-length text. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String imageUrl;

    /**
     * Zero-based display order controlling the image carousel sequence.
     * A value of {@code 0} indicates the primary (hero) image.
     */
    @Column(nullable = false)
    @Builder.Default
    private Integer displayOrder = 0;

    /** Optional alternative text used for accessibility (alt attribute). */
    private String altText;
}
