package com.sourabh.product_service.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * JPA entity representing a purchasable variant of a {@link Product}.
 * <p>
 * Variants capture product options such as size, colour, or material.
 * Each variant can optionally override the base product price and maintains
 * its own independent stock level. A composite unique constraint on
 * {@code (product_id, variant_name, variant_value)} prevents duplicate
 * combinations.
 * </p>
 * <p>
 * Inherits audit timestamps ({@code createdAt}, {@code updatedAt}) from
 * {@link BaseAuditEntity}.
 * </p>
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "product_variant",
       uniqueConstraints = @UniqueConstraint(columnNames = {"product_id", "variant_name", "variant_value"}))
public class ProductVariant extends BaseAuditEntity {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Universally unique identifier exposed to API consumers. */
    @Column(unique = true, nullable = false)
    private String uuid;

    /**
     * The parent product that this variant belongs to.
     * Fetched lazily to avoid unnecessary joins.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Name of the variant dimension (e.g. "Size", "Color", "Material"). */
    @Column(nullable = false)
    private String variantName;

    /** Specific value within the variant dimension (e.g. "XL", "Red", "Cotton"). */
    @Column(nullable = false)
    private String variantValue;

    /**
     * Optional price override for this variant.
     * When {@code null}, the base product price is used at checkout.
     */
    private Double priceOverride;

    /** Current available stock for this specific variant. */
    @Column(nullable = false)
    @Builder.Default
    private Integer stock = 0;

    /** Stock Keeping Unit code uniquely identifying this variant in inventory systems. */
    @Column(nullable = false, length = 20)
    private String sku;

    /** Whether this variant is currently available for purchase. */
    @Column(nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    /**
     * JPA lifecycle callback that generates a random UUID before the entity is
     * first persisted, if one has not already been assigned.
     */
    @PrePersist
    private void generateUuid() {
        if (uuid == null) uuid = java.util.UUID.randomUUID().toString();
    }
}
