package com.sourabh.product_service.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * JPA entity representing a product in the e-commerce catalogue.
 * <p>
 * Each product is created by a seller, reviewed and approved by an admin,
 * and can be purchased by buyers. The entity supports soft-deletion via the
 * {@code isDeleted} flag, and aggregated review metrics ({@code averageRating},
 * {@code totalReviews}) are updated asynchronously through Kafka events.
 * </p>
 * <p>
 * Inherits audit timestamps ({@code createdAt}, {@code updatedAt}) from
 * {@link BaseAuditEntity}.
 * </p>
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product extends BaseAuditEntity {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Universally unique identifier exposed to external API consumers. */
    @Column(unique = true, nullable = false)
    private String uuid;

    /** Human-readable product name displayed in listings and search results. */
    @Column(nullable = false)
    private String name;

    /** Detailed product description (up to 2 000 characters). */
    @Column(length = 2000)
    private String description;

    /** Base price of the product in the platform's default currency. */
    @Column(nullable = false)
    private Double price;

    /** Current available stock quantity; decremented on purchase, restored on cancellation. */
    @Column(nullable = false)
    private Integer stock;

    /** Legacy text category name kept for backward compatibility with older queries. */
    @Column(nullable = false)
    private String category;

    /**
     * Normalised reference to the {@link Category} entity.
     * Fetched lazily to avoid unnecessary joins during simple product reads.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category categoryRef;

    /** UUID of the seller who owns this product. */
    @Column(nullable = false)
    private String sellerUuid;

    /** Current lifecycle status of the product (DRAFT, ACTIVE, BLOCKED, OUT_OF_STOCK). */
    @Enumerated(EnumType.STRING)
    private ProductStatus status;

    /** Soft-delete flag; {@code true} hides the product from all public queries. */
    @Builder.Default
    private Boolean isDeleted = false;

    /** Running average of all review ratings for this product (0.0–5.0). */
    @Column(nullable = false)
    @Builder.Default
    private Double averageRating = 0.0;

    /** Total number of reviews submitted for this product. */
    @Column(nullable = false)
    @Builder.Default
    private Integer totalReviews = 0;

    /** URL of the primary product image, stored as unlimited-length text. */
    @Column(columnDefinition = "TEXT")
    private String imageUrl;

    /** Stock level below which the product is considered low-stock (default 10). */
    @Builder.Default
    private Integer lowStockThreshold = 10;

}
