package com.sourabh.product_service.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * JPA entity recording an individual stock level change for audit and traceability.
 * <p>
 * Every stock mutation—whether from a sale, restock, manual adjustment, or
 * reservation—is captured as an immutable {@code StockMovement} row. The
 * {@code stockAfter} field provides a running snapshot of the product's
 * inventory level after the movement, enabling straightforward audit trails.
 * </p>
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "stock_movement")
public class StockMovement {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** UUID of the product whose stock was affected. */
    @Column(nullable = false)
    private String productUuid;

    /** Type of stock movement that occurred. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MovementType type;

    /** Absolute quantity involved in this movement (always positive). */
    @Column(nullable = false)
    private Integer quantity;

    /** Product stock level immediately after this movement was applied. */
    @Column(nullable = false)
    private Integer stockAfter;

    /** Optional reference identifier (e.g. order UUID, adjustment note). */
    private String reference;

    /** Timestamp when this movement was recorded; defaults to the current time. */
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Enumeration of supported stock movement types.
     * <p>
     * Each type represents a distinct business reason for a stock change:
     * <ul>
     *   <li>{@link #SALE} – stock reduced when an order is placed</li>
     *   <li>{@link #RESTORATION} – stock restored after order cancellation or payment failure</li>
     *   <li>{@link #RESTOCK} – seller replenishes inventory</li>
     *   <li>{@link #ADJUSTMENT} – manual correction by seller or admin</li>
     *   <li>{@link #RESERVATION} – stock temporarily held during checkout</li>
     *   <li>{@link #RELEASE} – reserved stock released after timeout or cancellation</li>
     * </ul>
     * </p>
     */
    public enum MovementType {
        /** Stock reduced via a completed order. */
        SALE,
        /** Stock restored due to a cancelled order or failed payment. */
        RESTORATION,
        /** Seller added more stock. */
        RESTOCK,
        /** Manual admin or seller stock correction. */
        ADJUSTMENT,
        /** Stock temporarily reserved during checkout. */
        RESERVATION,
        /** Previously reserved stock released (timeout or cancellation). */
        RELEASE
    }
}
