package com.sourabh.user_service.dto.response;

import com.sourabh.user_service.entity.NotificationType;
import lombok.Builder;
import lombok.Getter;

import java.time.LocalDateTime;

/**
 * Response payload representing a user notification entry.
 *
 * <p>Notifications are generated by various domain events (order status
 * changes, ticket updates, promotions, etc.) and stored for later
 * retrieval. The {@link #isRead} flag tracks whether the user has
 * acknowledged the notification.</p>
 */
@Getter
@Builder
public class NotificationResponse {

    /** Unique identifier of the notification. */
    private String uuid;

    /** Category of the notification (e.g. ORDER, TICKET, PROMO). */
    private NotificationType type;

    /** Short headline displayed in the notification list. */
    private String title;

    /** Detailed notification body. */
    private String message;

    /** Optional reference ID linking to the related entity (e.g. order UUID). */
    private String referenceId;

    /** {@code true} if the user has already read this notification. */
    private boolean isRead;

    /** Timestamp when the notification was created. */
    private LocalDateTime createdAt;
}
