package com.sourabh.auth_service.controller;

import com.sourabh.auth_service.dto.request.ForgotPasswordRequest;
import com.sourabh.auth_service.dto.request.LoginRequest;
import com.sourabh.auth_service.dto.request.ResetPasswordRequest;
import com.sourabh.auth_service.dto.response.AuthResponse;
import com.sourabh.auth_service.service.AuthService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * AUTHENTICATION CONTROLLER
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * PURPOSE:
 * --------
 * REST API endpoints for user authentication and session management.
 * This controller exposes three core authentication operations:
 *   1. Login - Validates credentials and issues JWT token pair
 *   2. Refresh - Rotates tokens for session renewal without re-login
 *   3. Logout - Revokes refresh tokens to terminate sessions
 * 
 * ANNOTATIONS EXPLAINED:
 * ----------------------
 * 
 * @RestController:
 *   - Combines @Controller (marks this as Spring MVC controller) and
 *     @ResponseBody (automatically serializes return values to JSON/XML)
 *   - All methods return data directly in HTTP response body
 *   - Uses Jackson library to convert Java objects to JSON
 *   - Enables RESTful API development without manual response writing
 * 
 * @RequestMapping("/api/auth"):
 *   - Sets base path for all endpoints in this controller
 *   - All methods inherit this prefix (e.g., /api/auth/login)
 *   - Centralizes URL structure for easier refactoring
 *   - Can specify HTTP methods, headers, produces/consumes types
 * 
 * @RequiredArgsConstructor (Lombok):
 *   - Generates constructor with parameters for all 'final' fields
 *   - Enables constructor-based dependency injection (recommended over field injection)
 *   - Spring automatically injects dependencies via this constructor
 *   - Cleaner than @Autowired, makes dependencies explicit and testable
 *   - Example: private final AuthService authService -> constructor param
 * 
 * @Slf4j (Lombok):
 *   - Automatically creates a logger field: private static final Logger log
 *   - Uses SLF4J (Simple Logging Facade for Java) API
 *   - Backed by Logback implementation (configured in logback-spring.xml)
 *   - Enables structured logging: log.info(), log.error(), log.debug()
 *   - Supports parameterized logging for performance: log.info("User {}", email)
 * 
 * SECURITY:
 * ---------
 * - All requests must pass through API Gateway first
 * - Gateway validates JWT tokens and forwards with X-User-Uuid, X-User-Role headers
 * - This service is protected by InternalSecretFilter (X-Internal-Secret header)
 * - Only internal service-to-service calls are allowed
 * - Public endpoints are exposed through API Gateway routing
 * 
 * API FLOW:
 * ---------
 * Client -> API Gateway (JWT validation) -> Auth Service (credential validation)
 *   -> User Service (fetch user data) -> Auth Service (token generation) -> Client
 * 
 * ═══════════════════════════════════════════════════════════════════════════
 */
// REST API Controller - Handles HTTP requests and responses
@RestController                        // Marks this as REST API controller with JSON responses
@RequestMapping("/api/auth")          // Base path for all endpoints
@RequiredArgsConstructor              // Lombok: generates constructor for dependency injection
@Slf4j                                // Lombok: creates 'log' field for logging
public class AuthController {

    // Dependency: Business logic layer for authentication operations
    // Injected via constructor (generated by @RequiredArgsConstructor)
    private final AuthService authService;

    /**
     * ─────────────────────────────────────────────────────────────
     * LOGIN ENDPOINT
     * ─────────────────────────────────────────────────────────────
     * 
     * HTTP Method: POST
     * Path: /api/auth/login
     * 
     * PURPOSE:
     * Authenticates user credentials and issues JWT token pair.
     * 
     * REQUEST BODY:
     * {
     *   "email": "user@example.com",
     *   "password": "SecurePass123"
     * }
     * 
     * RESPONSE (200 OK):
     * {
     *   "accessToken": "eyJhbGciOiJIUzI1NiIs...",
     *   "refreshToken": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
     *   "tokenType": "Bearer"
     * }
     * 
     * PROCESS FLOW:
     * 1. @Valid triggers validation on LoginRequest (email format, required fields)
     * 2. AuthService fetches user from user-service via internal REST call
     * 3. Compares hashed password using BCrypt
     * 4. Generates JWT access token (expires in 15 minutes, configurable)
     * 5. Creates refresh token (expires in 7 days, configurable)
     * 6. Stores refresh token in database
     * 7. Returns token pair to client
     * 
     * ERROR RESPONSES:
     * - 400 Bad Request: Invalid email format or missing fields
     * - 401 Unauthorized: Invalid credentials
     * - 403 Forbidden: Email not verified or account inactive
     * 
     * ANNOTATIONS:
     * 
     * @PostMapping("/login"):
     *   - Shortcut for @RequestMapping(method = RequestMethod.POST)
     *   - Maps HTTP POST requests to this method
     *   - Full path: /api/auth/login (base + method path)
     * 
     * @Valid:
     *   - Triggers Bean Validation (JSR-380) on the request body
     *   - Validates @NotBlank, @Email, etc. on LoginRequest fields
     *   - If validation fails, throws MethodArgumentNotValidException
     *   - Caught by GlobalExceptionHandler and returns 400 with error details
     * 
     * @RequestBody:
     *   - Binds HTTP request body to method parameter
     *   - Uses Jackson to deserialize JSON to LoginRequest object
     *   - Automatically handles Content-Type: application/json
     */
    /**

     * API ENDPOINT

     * 

     * HTTP Method: POST

     * 

     * PURPOSE:

     * Handles HTTP requests for this endpoint. Validates input, delegates to service

     * layer for business logic, and returns JSON response.

     * 

     * PROCESS FLOW:

     * 1. API Gateway forwards request after JWT validation

     * 2. Spring deserializes JSON to request object

     * 3. @Valid triggers bean validation (if present)

     * 4. @PreAuthorize checks user role (if present)

     * 5. Service layer executes business logic

     * 6. Response object serialized to JSON

     * 7. HTTP status code sent (200/201/400/403/404/500)

     * 

     * SECURITY:

     * - JWT validation at API Gateway (user authenticated)

     * - Role-based access via @PreAuthorize annotation

     * - Input validation via @Valid and constraint annotations

     * 

     * ERROR HANDLING:

     * - Service exceptions caught by GlobalExceptionHandler

     * - Returns standardized error response with HTTP status

     */

    @PostMapping("/login")
    /**
     * LOGIN - Method Documentation
     *
     * PURPOSE:
     * This method handles the login operation.
     *
     * PARAMETERS:
     * @param request - @Valid @RequestBody LoginRequest value
     *
     * RETURN VALUE:
     * @return ResponseEntity<AuthResponse> - Result of the operation
     *
     * ANNOTATIONS USED:
     * @PostMapping - REST endpoint handler
     *
     */
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest request) {
        // Delegate to service layer for business logic
        // ResponseEntity.ok() creates 200 OK response with body
        return ResponseEntity.ok(authService.login(request));
    }

    /**
     * ─────────────────────────────────────────────────────────────
     * REFRESH TOKEN ENDPOINT
     * ─────────────────────────────────────────────────────────────
     * 
     * HTTP Method: POST
     * Path: /api/auth/refresh?refreshToken=<token>
     * 
     * PURPOSE:
     * Rotates expired access token without requiring re-login.
     * Implements secure token rotation pattern (revokes old, issues new).
     * 
     * QUERY PARAMETER:
     * - refreshToken: UUID string from previous login/refresh response
     * 
     * RESPONSE (200 OK):
     * {
     *   "accessToken": "eyJhbGciOiJIUzI1NiIs..." (new),
     *   "refreshToken": "9876fedc-ba09-8765-4321-fedcba987654" (new),
     *   "tokenType": "Bearer"
     * }
     * 
     * PROCESS FLOW:
     * 1. Validates refresh token exists and not revoked
     * 2. Checks expiry date (not expired)
     * 3. Fetches user from user-service to verify account still active
     * 4. Revokes old refresh token (sets revoked=true)
     * 5. Generates new access token and new refresh token
     * 6. Stores new refresh token in database
     * 7. Returns new token pair
     * 
     * SECURITY:
     * Token rotation prevents token reuse attacks. If a refresh token is
     * used after being rotated, it indicates potential token theft.
     * 
     * ERROR RESPONSES:
     * - 401 Unauthorized: Invalid, expired, or revoked refresh token
     * - 403 Forbidden: User account no longer active
     * 
     * ANNOTATIONS:
     * 
     * @RequestParam:
     *   - Binds query parameter to method parameter
     *   - Example: ?refreshToken=abc123 -> String refreshToken = "abc123"
     *   - Required by default (returns 400 if missing)
     *   - Can make optional: @RequestParam(required = false)
     */
    @PostMapping("/refresh")
    /**
     * REFRESH - Method Documentation
     *
     * PURPOSE:
     * This method handles the refresh operation.
     *
     * PARAMETERS:
     * @param refreshToken - @RequestParam String value
     *
     * RETURN VALUE:
     * @return ResponseEntity<AuthResponse> - Result of the operation
     *
     * ANNOTATIONS USED:
     * @RequestParam - Applied to this method
     * @RequestParam - Applied to this method
     * @PostMapping - REST endpoint handler
     *
     */
    public ResponseEntity<AuthResponse> refresh(@RequestParam String refreshToken) {
        // Token rotation: old token revoked, new pair issued
        return ResponseEntity.ok(authService.refreshToken(refreshToken));
    }

    /**
     * ─────────────────────────────────────────────────────────────
     * LOGOUT ENDPOINT
     * ─────────────────────────────────────────────────────────────
     * 
     * HTTP Method: POST
     * Path: /api/auth/logout?refreshToken=<token>
     * 
     * PURPOSE:
     * Terminates user session by revoking refresh token.
     * Access tokens cannot be revoked (stateless), but they expire quickly (15 min).
     * 
     * QUERY PARAMETER:
     * - refreshToken: Token to revoke
     * 
     * RESPONSE (204 No Content):
     * Empty response body, status 204 indicates success.
     * 
     * PROCESS FLOW:
     * 1. Finds refresh token in database
     * 2. Sets revoked=true (prevents future use)
     * 3. Saves updated token
     * 
     * SECURITY NOTE:
     * - Access tokens remain valid until expiration (stateless design)
     * - For critical operations, always check account status in real-time
     * - Consider maintaining a token blacklist for emergency revocation
     * 
     * ERROR RESPONSES:
     * - 401 Unauthorized: Invalid refresh token
     * 
     * ANNOTATIONS:
     * 
     * ResponseEntity<Void>:
     *   - Generic type Void for empty response body
     *   - noContent() returns 204 status (success with no body)
     *   - Alternative to ok() when no data needs to be returned
     */
    @PostMapping("/logout")
    /**
     * LOGOUT - Method Documentation
     *
     * PURPOSE:
     * This method handles the logout operation.
     *
     * PARAMETERS:
     * @param refreshToken - @RequestParam String value
     *
     * RETURN VALUE:
     * @return ResponseEntity<Void> - Result of the operation
     *
     * ANNOTATIONS USED:
     * @PostMapping - REST endpoint handler
     *
     */
    public ResponseEntity<Void> logout(@RequestParam String refreshToken) {
        // Revoke refresh token to prevent further use
        authService.logout(refreshToken);
        // 204 No Content - successful operation, no response body
        return ResponseEntity.noContent().build();
    }

    // ─────────────────────────────────────────────
    // FORGOT PASSWORD
    // ─────────────────────────────────────────────

    @PostMapping("/forgot-password")
    public ResponseEntity<String> forgotPassword(@Valid @RequestBody ForgotPasswordRequest request) {
        return ResponseEntity.ok(authService.forgotPassword(request));
    }

    @PostMapping("/reset-password")
    public ResponseEntity<String> resetPassword(@Valid @RequestBody ResetPasswordRequest request) {
        return ResponseEntity.ok(authService.resetPassword(request));
    }
}
