#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$ROOT_DIR/docs/COMPLETE_CODE_REFERENCE.md"

cd "$ROOT_DIR"

mkdir -p docs

mapfile -t FILES < <(find . -type f \
  \( -name "*.java" -o -name "*.properties" -o -name "*.yml" -o -name "*.yaml" -o -name "*.sql" -o -iname "dockerfile" -o -name "pom.xml" \) \
  -not -path "*/target/*" \
  -not -path "*/.git/*" \
  | sed 's|^./||' \
  | sort)

anchorize() {
  printf "%s" "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

{
  echo "# Complete Code Reference"
  echo
  echo "This document is auto-generated by \`scripts/generate_full_reference.sh\`."
  echo
  echo "- Included files: ${#FILES[@]}"
  echo "- Scope: Java source, Spring/infra configs, SQL, Dockerfiles, Maven POMs"
  echo "- Excluded: \`target/\`, \`.git/\`"
  echo
  echo "## File Index"
  echo
  for f in "${FILES[@]}"; do
    echo "- [$f](#$(anchorize "$f"))"
  done

  for f in "${FILES[@]}"; do
    ext="${f##*.}"
    lang="text"

    case "$ext" in
      java) lang="java" ;;
      properties) lang="properties" ;;
      yml|yaml) lang="yaml" ;;
      sql) lang="sql" ;;
      xml) lang="xml" ;;
      *)
        if [[ "$(basename "$f" | tr '[:upper:]' '[:lower:]')" == "dockerfile" ]]; then
          lang="dockerfile"
        fi
        ;;
    esac

    echo
    echo "## $f"
    echo
    echo "Path: \`$f\`"
    echo
    echo "\`\`\`${lang}"
    nl -ba "$f"
    echo "\`\`\`"
  done
} > "$OUT_FILE"

echo "Generated: $OUT_FILE"
echo "Files included: ${#FILES[@]}"