server.port=8080
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:5432/payment_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api/payment/v3/api-docs
springdoc.swagger-ui.enabled=false
logging.level.com.sourabh.payment_service=INFO

# enable test gateway and credentials
payment.gateway=razorpay
razorpay.key-id=rzp_test_SL4AEW6qEGJMfX
razorpay.key-secret=TzESHfJw1xNOoQLlHLrgwQ7Q
