spring.application.name=review-service

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/review_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

internal.secret=veryStrongInternalSecret123
